workflows:
  react-native-android:
    name: Android Production Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - shentaokey
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "shengram.shentao.it"
        GOOGLE_PLAY_TRACK: production
      node: 16

    scripts:
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Clean React Native cache
        script: |
          npx react-native start --reset-cache &
          sleep 5
          pkill -f "react-native start" || true

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER

    artifacts:
      - android/app/build/outputs/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false

      email:
        recipients:
          - gobbi.francesco.04@gmail.com
        notify:
          success: true
          failure: true

  react-native-ios:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: shengram.shentao.it
      vars:
        BUNDLE_ID: "shengram.shentao.it"
        XCODE_WORKSPACE: "InstagramClone.xcworkspace"
        XCODE_SCHEME: "InstagramClone"
        APP_STORE_APPLE_ID: 6744418206
      node: 16
      cocoapods: default

    integrations:
      app_store_connect: shentao

    scripts:
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Clean React Native cache
        script: |
          npx react-native start --reset-cache &
          sleep 5
          pkill -f "react-native start" || true

      - name: Update CocoaPods repo
        script: |
          pod repo update

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Configure code signing
        script: |
          xcode-project use-profiles

      - name: Increment build number
        script: |
          cd ios
          agvtool new-version -all $BUILD_NUMBER

      - name: Build IPA for App Store
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --output-dir "$CM_BUILD_DIR/ios/build"

    artifacts:
      - ios/build/*.ipa
      - ios/**/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - tester
        submit_to_app_store: true

      email:
        recipients:
          - gobbi.francesco.04@gmail.com
        notify:
          success: true
          failure: true
