workflows:
    ios-workflow:
        name: Codemagic IOS Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        
    android-workflow:
        name: Codemagic ANDROID Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          android_signing:
             - shentaokey